### ISSUE TITLE
how to navigate faster in insert mode ?

### ISSUE THREAD

**Issue by ghost** [shawncplus/vim-classes#2]
hjkl?

**Comment by shawncplus** [comment]
My answer, frankly, is "don't". If I have to move I do it in normal mode.

**Comment by ghost** [comment]
Could I use k navigate down, and j navigate up? i find this could be more efficient.

**Comment by shawncplus** [comment]
Not in insert mode. My dotfiles are really only as a backup for me. If you're new to vim I absolutely _do not_ recommend using them. Standard vim will let you move in insert mode with the arrow keys but I never use them and find them to teach bad practices so my dotfiles disable them.
